// Montagem principal da aplicacao Zend clonada.
// Este arquivo conecta configuracoes, eventos, paineis e interacoes.
// O index.js fica responsavel apenas por chamar iniciarBot().
//
// Branding: Flow Vazamentos · .gg/flowvazamentos
// (módulo obrigatório: src/infraestrutura/creditos.js — não remover)

import {
  ActionRowBuilder,
  AttachmentBuilder,
  ButtonStyle,
  ChannelSelectMenuBuilder,
  ChannelType,
  Client,
  ContainerBuilder,
  EmbedBuilder,
  GatewayIntentBits,
  MediaGalleryBuilder,
  MediaGalleryItemBuilder,
  MessageFlags,
  PermissionFlagsBits,
  RoleSelectMenuBuilder,
  SeparatorBuilder,
  StringSelectMenuBuilder,
  TextDisplayBuilder,
  TextInputStyle,
} from 'discord.js';
import { createCanvas } from '@napi-rs/canvas';
import { existsSync } from 'node:fs';
import fs from 'node:fs/promises';
import path from 'node:path';
import { EXTENSOES_EMOJI_ZEND, PASTA_EMOJIS_ZEND } from '../configuracoes/emojis-zend.js';
import { TEMAS_CORES_ZEND } from '../configuracoes/temas-zend.js';
import { CANAIS_AUTOMATICOS_ZEND } from '../configuracoes/canais-zend.js';
import { ASSETS, localAsset } from '../configuracoes/assets-zend.js';
import { CLIENT_ID, GUILD_ID, SYNC_EMOJIS_ONLY, SYNC_EMOJIS_ON_START, TOKEN, validarAmbiente } from '../configuracoes/ambiente.js';
import { EMOJI, POSITION_EMOJIS, POSITION_LIMIT, applySyncedEmojiOverrides, configurarPersistenciaEmoji, emojiSyncSummary, emojiTag, renderCustomEmojis, syncLocalEmojis, syncedEmojiOptions } from '../discord/emojis.js';
import { button, embed, id, linkButton, modal, money, nowFooter, rows, textInput } from '../discord/componentes.js';
import { defaultGuildState, guildState, saveState, state, userDraft } from '../database/estado.js';
import { getField, getProduct } from '../database/repositorios.js';
import { registerCommands } from '../comandos/slash-commands.js';
import { criarExecutorSlash } from '../comandos/executor-slash.js';
import { registrarEventoBotPronto } from '../eventos/bot-pronto.js';
import { registrarEventoEntradaMembro } from '../eventos/entrada-membro.js';
import { registrarEventoInteracoes } from '../eventos/interacoes.js';
import { registrarEventosAutomacoes } from '../eventos/automacoes.js';
import { registrarSelfBan } from '../eventos/selfban-monitor.js';
import { sendOrUpdate } from '../infraestrutura/envio-interacao.js';
import { parseHex, renderFeedback, renderWelcome } from '../utilidades/formatacao.js';
import { criarLogsDeVendas } from '../logs/vendas.js';
import { criarSistemaCarrinho } from '../loja/carrinho.js';
import { criarHandlerBotoes } from '../interacoes/botoes.js';
import { criarHandlersMenus } from '../interacoes/menus.js';
import { criarHandlerModais } from '../interacoes/modais.js';
import { criarPaineisZend } from '../paineis/paineis-zend.js';
import { iniciarAgendadorAutomacoes } from '../automacoes/servico-automacoes.js';
import { patchInteracoesDiscord } from '../infraestrutura/patch-interacoes.js';
import { garantirCreditos } from '../infraestrutura/creditos.js';
import { iniciarAgendadorSorteios } from '../sorteios/sorteio-v2.js';

// Branding Flow — se falhar, o bot não sobe
garantirCreditos();

// ephemeral → flags + ignora interação expirada (10062)
patchInteracoesDiscord();

configurarPersistenciaEmoji(saveState);




const carrinhoApi = {};

const {
  sendConfiguredLog,
  editStockButton,
  sendManualApprovalLog,
  sendOrderRequestedLog,
  sendBuyerDeliveryDm,
  sendOutOfStockLog,
  sendDeliveryLog,
  sendApprovalLog,
} = criarLogsDeVendas({
  ActionRowBuilder,
  ButtonStyle,
  EmbedBuilder,
  EMOJI,
  button,
  cartAmounts: (...args) => carrinhoApi.cartAmounts(...args),
  cartField: (...args) => carrinhoApi.cartField(...args),
  cartItemName: (...args) => carrinhoApi.cartItemName(...args),
  cartProduct: (...args) => carrinhoApi.cartProduct(...args),
  embed,
  id,
  linkButton,
  money,
  parseHex,
  renderFeedback,
});

const paineisZend = criarPaineisZend({
  ActionRowBuilder,
  AttachmentBuilder,
  ButtonStyle,
  ChannelSelectMenuBuilder,
  ChannelType,
  ContainerBuilder,
  EmbedBuilder,
  MediaGalleryBuilder,
  MediaGalleryItemBuilder,
  MessageFlags,
  PermissionFlagsBits,
  RoleSelectMenuBuilder,
  SeparatorBuilder,
  StringSelectMenuBuilder,
  TextDisplayBuilder,
  TextInputStyle,
  ASSETS,
  CANAIS_AUTOMATICOS_ZEND,
  EMOJI,
  EXTENSOES_EMOJI_ZEND,
  PASTA_EMOJIS_ZEND,
  POSITION_EMOJIS,
  POSITION_LIMIT,
  TEMAS_CORES_ZEND,
  button,
  createCanvas,
  embed,
  existsSync,
  fs,
  id,
  linkButton,
  localAsset,
  modal,
  money,
  nowFooter,
  parseHex,
  path,
  renderCustomEmojis,
  renderWelcome,
  rows,
  saveState,
  sendConfiguredLog,
  syncedEmojiOptions,
  textInput,
});

const {
  mainPanel,
  productListPanel,
  storePanel,
  authPanel,
  positionsPanel,
  positionPanel,
  balancePanel,
  storeCouponsPanel,
  badgesPanel,
  tempRolePanel,
  storeOauthPanel,
  draftProductPanel,
  productPanel,
  stockCount,
  fieldsPanel,
  fieldPanel,
  fieldEmojiPanel,
  stockPanel,
  couponsPanel,
  ticketPanel,
  welcomePanel,
  automationsPanel,
  repostPanel,
  automationFeaturePanel,
  customPanel,
  customDetailPanel,
  statementPanel,
  statementPeriodPanel,
  statementHistoryPanel,
  statementChartPanel,
  giveawayPanel,
  giveawayDurationPanel,
  giveawayChannelPanel,
  giveawayRolesPanel,
  giveawayExtrasPanel,
  giveawayMessagePayload,
  giveawayManagePanel,
  giveawayDetailPanel,
  finishGiveaway,
  scheduleGiveaway,
  parseDuration,
  settingsPanel,
  rolesConfigPanel,
  roleSelectionPanel,
  channelsPanel,
  channelSelectionPanel,
  zenWalletPanel,
  paymentsPanel,
  manualPaymentPanel,
  gatewayPaymentPanel,
  antiFakePanel,
  cloudPanel,
  oauthPanel,
  oauthConfigPanel,
  oauthRolePanel,
  protectPanel,
  protectDetailPanel,
  protectSelfBotPanel,
  protectAntiInvitePanel,
  protectChannelSelectionPanel,
  protectWhitelistPanel,
  simplePanel,
  rolesFieldPanel,
  fieldRolePickerPanel,
  conditionsPanel,
  conditionRolePickerPanel,
  stockRemovePanel,
  ticketOpeningPayload,
  ticketPreview,
  openTicket,
  ticketFunctionsPanel,
  ticketFunctionDetailPanel,
  ticketOpenModePanel,
  ticketHoursPanel,
  ticketStatsPanel,
  ticketHelpEmbed,
  channelSelectRow,
  salePayload,
  parsePrice
} = paineisZend;

const executorSlash = criarExecutorSlash({
  ActionRowBuilder,
  ButtonStyle,
  EMOJI,
  PermissionFlagsBits,
  StringSelectMenuBuilder,
  button,
  deliverCart: (...args) => carrinhoApi.deliverCart(...args),
  embed,
  emojiSyncSummary,
  fieldPanel,
  getCart: (...args) => carrinhoApi.getCart(...args),
  id,
  isCartAdmin: (...args) => carrinhoApi.isCartAdmin(...args),
  mainPanel,
  money,
  parseHex,
  productPanel,
  salePayload,
  statementPanel,
  stockCount,
  stockPanel,
  syncLocalEmojis,
  zenWalletPanel,
});

const {
  handleSlashCommand,
  helpPanel,
  balanceUser,
  moveBalance,
  outOfStockEmbed,
  balancePublicPayload,
} = executorSlash;

const {
  CART_TERMINAL_STATUSES,
  CART_EDITABLE_STATUSES,
  getCart,
  cartProduct,
  cartField,
  availableStock,
  clampCartQuantity,
  findCartCoupon,
  cartAmounts,
  cartItemName,
  cartPayload,
  isCartOwner,
  isCartAdmin,
  createCartChannel,
  refreshCartMessage,
  syncSaleMessage,
  deliverCart,
  startCart,
  handleCartButton,
} = criarSistemaCarrinho({
  ActionRowBuilder,
  ButtonStyle,
  ChannelType,
  ContainerBuilder,
  EMOJI,
  EmbedBuilder,
  MessageFlags,
  PermissionFlagsBits,
  SeparatorBuilder,
  StringSelectMenuBuilder,
  TextDisplayBuilder,
  TextInputStyle,
  balanceUser,
  button,
  embed,
  guildState,
  id,
  linkButton,
  modal,
  money,
  nowFooter,
  salePayload,
  sendApprovalLog,
  sendBuyerDeliveryDm,
  sendConfiguredLog,
  sendDeliveryLog,
  sendManualApprovalLog,
  sendOrderRequestedLog,
  sendOutOfStockLog,
  stockCount,
  textInput,
});

Object.assign(carrinhoApi, { cartAmounts, cartField, cartItemName, cartProduct, deliverCart, getCart, isCartAdmin });

const handleModal = criarHandlerModais({
  ActionRowBuilder,
  ButtonStyle,
  CART_EDITABLE_STATUSES,
  EMOJI,
  EmbedBuilder,
  TextInputStyle,
  antiFakePanel,
  automationFeaturePanel,
  authPanel,
  availableStock,
  badgesPanel,
  button,
  cartAmounts,
  cartField,
  cartPayload,
  cartProduct,
  channelSelectRow,
  clampCartQuantity,
  conditionsPanel,
  couponsPanel,
  customDetailPanel,
  draftProductPanel,
  embed,
  fieldPanel,
  fieldsPanel,
  findCartCoupon,
  finishGiveaway,
  gatewayPaymentPanel,
  getCart,
  getField,
  getProduct,
  giveawayChannelPanel,
  giveawayDetailPanel,
  giveawayDurationPanel,
  giveawayManagePanel,
  giveawayMessagePayload,
  id,
  isCartAdmin,
  isCartOwner,
  linkButton,
  mainPanel,
  manualPaymentPanel,
  modal,
  money,
  moveBalance,
  oauthConfigPanel,
  oauthPanel,
  parseDuration,
  parseHex,
  parsePrice,
  positionPanel,
  productPanel,
  protectDetailPanel,
  protectSelfBotPanel,
  refreshCartMessage,
  repostPanel,
  rolesConfigPanel,
  rolesFieldPanel,
  sendApprovalLog,
  sendOrUpdate,
  stockPanel,
  storeCouponsPanel,
  storeOauthPanel,
  syncSaleMessage,
  tempRolePanel,
  textInput,
  ticketFunctionDetailPanel,
  ticketFunctionsPanel,
  ticketHoursPanel,
  ticketPanel,
  userDraft,
  welcomePanel,
});

const { handleSelect, handleChannelSelect } = criarHandlersMenus({
  ActionRowBuilder,
  ButtonStyle,
  CART_EDITABLE_STATUSES,
  ChannelType,
  EMOJI,
  StringSelectMenuBuilder,
  TEMAS_CORES_ZEND,
  TextInputStyle,
  availableStock,
  badgesPanel,
  balancePanel,
  balancePublicPayload,
  button,
  cartAmounts,
  cartField,
  cartPayload,
  cartProduct,
  channelSelectionPanel,
  channelsPanel,
  clampCartQuantity,
  conditionsPanel,
  customDetailPanel,
  embed,
  emojiTag,
  fieldPanel,
  findCartCoupon,
  getCart,
  getField,
  getProduct,
  giveawayChannelPanel,
  giveawayDetailPanel,
  giveawayExtrasPanel,
  giveawayRolesPanel,
  helpPanel,
  id,
  isCartAdmin,
  isCartOwner,
  linkButton,
  modal,
  oauthConfigPanel,
  positionPanel,
  positionsPanel,
  productPanel,
  protectAntiInvitePanel,
  protectDetailPanel,
  protectSelfBotPanel,
  roleSelectionPanel,
  rolesConfigPanel,
  rolesFieldPanel,
  salePayload,
  sendOrUpdate,
  stockPanel,
  storeCouponsPanel,
  storeOauthPanel,
  syncSaleMessage,
  tempRolePanel,
  textInput,
  ticketFunctionDetailPanel,
  ticketFunctionsPanel,
  ticketHoursPanel,
  ticketOpenModePanel,
  ticketOpeningPayload,
  ticketPanel,
  ticketStatsPanel,
  userDraft,
  openTicket,
});

const handleButton = criarHandlerBotoes({
  ActionRowBuilder,
  ButtonStyle,
  CANAIS_AUTOMATICOS_ZEND,
  CART_EDITABLE_STATUSES,
  CART_TERMINAL_STATUSES,
  CLIENT_ID,
  ChannelType,
  EMOJI,
  EmbedBuilder,
  PermissionFlagsBits,
  TEMAS_CORES_ZEND,
  TextInputStyle,
  antiFakePanel,
  automationFeaturePanel,
  authPanel,
  automationsPanel,
  availableStock,
  badgesPanel,
  balancePanel,
  button,
  cartAmounts,
  cartField,
  cartPayload,
  cartProduct,
  channelSelectRow,
  channelsPanel,
  clampCartQuantity,
  cloudPanel,
  conditionRolePickerPanel,
  conditionsPanel,
  couponsPanel,
  customDetailPanel,
  customPanel,
  defaultGuildState,
  deliverCart,
  draftProductPanel,
  embed,
  emojiSyncSummary,
  fieldEmojiPanel,
  fieldPanel,
  fieldRolePickerPanel,
  fieldsPanel,
  findCartCoupon,
  finishGiveaway,
  gatewayPaymentPanel,
  getCart,
  getField,
  getProduct,
  giveawayDurationPanel,
  giveawayExtrasPanel,
  giveawayManagePanel,
  giveawayMessagePayload,
  giveawayPanel,
  giveawayRolesPanel,
  guildState,
  handleCartButton,
  id,
  isCartAdmin,
  isCartOwner,
  linkButton,
  mainPanel,
  manualPaymentPanel,
  modal,
  money,
  oauthConfigPanel,
  oauthPanel,
  oauthRolePanel,
  openTicket,
  outOfStockEmbed,
  parseDuration,
  parseHex,
  paymentsPanel,
  positionsPanel,
  productListPanel,
  productPanel,
  protectAntiInvitePanel,
  protectChannelSelectionPanel,
  protectDetailPanel,
  protectPanel,
  protectSelfBotPanel,
  protectWhitelistPanel,
  refreshCartMessage,
  renderWelcome,
  repostPanel,
  rolesConfigPanel,
  rolesFieldPanel,
  scheduleGiveaway,
  sendApprovalLog,
  sendConfiguredLog,
  sendOrUpdate,
  settingsPanel,
  simplePanel,
  startCart,
  statementChartPanel,
  statementHistoryPanel,
  statementPanel,
  statementPeriodPanel,
  stockCount,
  stockPanel,
  stockRemovePanel,
  storeOauthPanel,
  storePanel,
  syncLocalEmojis,
  syncSaleMessage,
  tempRolePanel,
  textInput,
  ticketFunctionDetailPanel,
  ticketFunctionsPanel,
  ticketHelpEmbed,
  ticketHoursPanel,
  ticketOpenModePanel,
  ticketOpeningPayload,
  ticketPanel,
  ticketPreview,
  ticketStatsPanel,
  userDraft,
  welcomePanel,
  zenWalletPanel,
});

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMembers,
    GatewayIntentBits.GuildInvites,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.GuildVoiceStates,
  ],
});

registrarEventoBotPronto(client, {
  state,
  applySyncedEmojiOverrides,
  iniciarAgendadorAutomacoes,
  saveState,
  scheduleGiveaway,
  syncEmojisOnStart: SYNC_EMOJIS_ON_START,
  guildId: GUILD_ID,
  guildState,
  syncLocalEmojis,
  syncEmojisOnly: SYNC_EMOJIS_ONLY,
});

registrarEventoEntradaMembro(client, { guildState, sendConfiguredLog, embed, parseHex, renderWelcome });
registrarEventosAutomacoes(client, { guildState, saveState, sendConfiguredLog, embed });



registrarEventoInteracoes(client, {
  guildState,
  handleSlashCommand,
  handleModal,
  handleSelect,
  handleChannelSelect,
  handleButton,
  saveState,
});



export const paineisParaTeste = {
  criarEstado: defaultGuildState,
  principal: mainPanel,
  loja: storePanel,
  tickets: ticketPanel,
  funcoesTicket: ticketFunctionsPanel,
  modoTicket: ticketOpenModePanel,
  horariosTicket: ticketHoursPanel,
  boasVindas: welcomePanel,
  personalizacao: customPanel,
  detalhePersonalizacao: customDetailPanel,
  extrato: statementPanel,
  graficoExtrato: statementChartPanel,
  sorteios: giveawayPanel,
  configuracoes: settingsPanel,
  canais: channelsPanel,
  pagamentos: paymentsPanel,
  nuvem: cloudPanel,
  protecao: protectPanel,
};

export async function iniciarBot() {
  validarAmbiente();
  await registerCommands({ token: TOKEN, clientId: CLIENT_ID, guildId: GUILD_ID });
  await client.login(TOKEN);
  registrarSelfBan(client);
  iniciarAgendadorSorteios(client);
}
